---
rabbitmq:
  username:
  password:
  host: rabbitmq
  port: 5672
  url:
  exchange: CryptoPricesTopicExchange
influxdb:
  url:
  username:
  password:
  host: influxdb
  port: 8086
  token:
  org: CryptoTrackerOrganisation
  bucket: CryptoTrackerBucket
redis:
  password:
  host: redis
  port: 6379
  url:
websocket:
  url: http://localhost:3008/notify
frontend:
  url: http://localhost:3000
