function getTakerFeeForVolume(exchange: string, volume: number) {
  var applicableFee = 0;
  if (exchange == "kraken") {
    const feeInfo = krakenTakerFees.find((fee) => volume < fee.volume);
    if (feeInfo) {
      applicableFee += feeInfo.fee;
      if (applicableFee != 0) {
        applicableFee /= 100;
      }
    }
  }
  if (exchange == "bitstamp") {
    const feeInfo = bitstampTakerFees.find((fee) => volume < fee.volume);
    if (feeInfo) {
      applicableFee += feeInfo.fee;
      if (applicableFee != 0) {
        applicableFee /= 100;
      }
    }
  }
  return applicableFee;
}
function getWithdrawlFee(exchange: string, asset: string) {
  var applicableFee = 0;
  if (exchange == "kraken") {
    const feeInfo = krakenWithdrawalFees.find((fee) => asset == fee.asset);
    if (feeInfo) {
      applicableFee += feeInfo.fee;
    }
  }
  if (exchange == "bitstamp") {
    const feeInfo = bitstampWidrawalFees.find((fee) => asset == fee.asset);
    if (feeInfo) {
      applicableFee += feeInfo.fee;
    }
  }
  return applicableFee;
}

export const calculateProfit = (
  symbol: string | undefined,
  price1: number | undefined,
  price2: number | undefined,
  amount: number,
  exchange1volume: number,
  exchange2volume: number,
  exchange1: string | undefined,
  exchange2: string | undefined,
) => {
  if (
    exchange1 == undefined ||
    exchange2 == undefined ||
    symbol == undefined ||
    price1 == undefined ||
    price2 == undefined
  ) {
    return 0;
  }
  const asset = symbol.split("/")[0];
  const fee1 = getTakerFeeForVolume(exchange1, exchange1volume);
  // console.log("Fee1 kosten", fee1);
  const fee2 = getTakerFeeForVolume(exchange2, exchange2volume);
  // console.log("Fee2 kosten", fee2);
  // console.log("Fee in exchange1 ", fee1, " fee in exchange2", fee2);
  // Zuerst wird der Taker fee abgezogen
  var newAmount = amount - amount * fee1;
  // console.log("Amount nach taker abzug", amount);
  // Anschließend werden die Assets umgerechnet
  newAmount /= price1;
  // console.log("Amount nach umrechnung", amount, "mit preise", price1);
  // Dann werden die Withdrawl fees abgezogen
  newAmount -= getWithdrawlFee(exchange1, asset);
  // console.log("Amount nach Withdrawl", amount, "vom asset", asset);
  // Dann werden die assets wieder umgerechnet
  newAmount *= price2;
  // console.log("Amount nach Umrechnung2", amount, "mit preis", price2);
  // Schließlich werden die zweiten fees abgezogen
  newAmount -= newAmount * fee2;
  // console.log("rest amount", amount);

  return (newAmount - amount).toFixed(2);
};

const krakenTakerFees = [
  { volume: 50000, fee: 0.26 },
  { volume: 100000, fee: 0.24 },
  { volume: 250000, fee: 0.22 },
  { volume: 500000, fee: 0.2 },
  { volume: 1000000, fee: 0.18 },
  { volume: 2500000, fee: 0.16 },
  { volume: 5000000, fee: 0.14 },
  { volume: 10000000, fee: 0.12 },
  { volume: 100000000, fee: 0.1 },
  { volume: 250000000, fee: 0.08 },
  { volume: 500000000, fee: 0.06 },
  { volume: Infinity, fee: 0.04 },
];

const bitstampTakerFees = [
  { volume: 1000, fee: 0 },
  { volume: 10000, fee: 0.4 },
  { volume: 100000, fee: 0.3 },
  { volume: 500000, fee: 0.2 },
  { volume: 1500000, fee: 0.18 },
  { volume: 5000000, fee: 0.16 },
  { volume: 20000000, fee: 0.12 },
  { volume: 50000000, fee: 0.1 },
  { volume: 100000000, fee: 0.08 },
  { volume: 250000000, fee: 0.06 },
  { volume: 1000000000, fee: 0.05 },
  { volume: Infinity, fee: 0.03 },
];

const krakenWithdrawalFees = [
  { asset: "ZRX", fee: 21 },
  { asset: "1INCH", fee: 11 },
  { asset: "AAVE", fee: 0.073 },
  { asset: "GHST", fee: 5.3 },
  { asset: "ACA", fee: 0.15 },
  { asset: "AGLD", fee: 9.6 },
  { asset: "AKT", fee: 0.5 },
  { asset: "ALCX", fee: 0.29 },
  { asset: "ACH", fee: 150 },
  { asset: "ALGO", fee: 0.1 },
  { asset: "TLM", fee: 270 },
  { asset: "AIR", fee: 3 },
  { asset: "ADX", fee: 30 },
  { asset: "FORTH", fee: 1.6 },
  { asset: "ANKR", fee: 170 },
  { asset: "APE", fee: 1.3 },
  { asset: "API3", fee: 3.5 },
  { asset: "APT", fee: 0.01 },
  { asset: "ANT", fee: 1.7 },
  { asset: "ARB", fee: 0.2 },
  { asset: "ARPA", fee: 140 },
  { asset: "ASTR", fee: 0.1 },
  { asset: "AUDIO", fee: 18 },
  { asset: "REP", fee: 0.73 },
  { asset: "REPV2", fee: 0.72 },
  { asset: "AVAX", fee: 0.05 },
  { asset: "AVT", fee: 2 },
  { asset: "AXS", fee: 0.67 },
  { asset: "BADGER", fee: 2 },
  { asset: "BAL", fee: 0.81 },
  { asset: "BNT", fee: 11 },
  { asset: "BAND", fee: 3.1 },
  { asset: "BOND", fee: 1.4 },
  { asset: "BAT", fee: 21 },
  { asset: "BSX", fee: 150 },
  { asset: "BICO", fee: 15 },
  { asset: "BNC", fee: 0.5 },
  { asset: "BTC", fee: 0.00005 },
  { asset: "BCH", fee: 0.0003 },
  { asset: "BIT", fee: 11 },
  { asset: "BLUR", fee: 9.8 },
  { asset: "BLZ", fee: 67 },
  { asset: "BTT", fee: 2.5 },
  { asset: "BOBA", fee: 26 },
  { asset: "FIDA", fee: 0.5 },
  { asset: "BRICK", fee: 6 },
  { asset: "ADA", fee: 1 },
  { asset: "CTSI", fee: 37 },
  { asset: "CELR", fee: 260 },
  { asset: "CFG", fee: 0.05 },
  { asset: "XCN", fee: 1500 },
  { asset: "LINK", fee: 0.78 },
  { asset: "CHZ", fee: 44 },
  { asset: "CHR", fee: 35 },
  { asset: "CVC", fee: 53 },
  { asset: "COMP", fee: 0.14 },
  { asset: "C98", fee: 22 },
  { asset: "CVX", fee: 1 },
  { asset: "ATOM", fee: 0.1 },
  { asset: "COTI", fee: 73 },
  { asset: "CQT", fee: 33 },
  { asset: "CSM", fee: 25 },
  { asset: "CRV", fee: 5.5 },
  { asset: "DASH", fee: 0.005 },
  { asset: "DAI", fee: 2 },
  { asset: "MANA", fee: 9.5 },
  { asset: "DENT", fee: 5100 },
  { asset: "DOGE", fee: 4 },
  { asset: "DYDX", fee: 2.2 },
  { asset: "EWT", fee: 0.26 },
  { asset: "ENJ", fee: 14 },
  { asset: "MLN", fee: 0.26 },
  { asset: "EOS", fee: 0.05 },
  { asset: "ETHW", fee: 0.05 },
  { asset: "ETC", fee: 0.008 },
  { asset: "ENS", fee: 0.43 },
  { asset: "EUL", fee: 1.6 },
  { asset: "FTM", fee: 0.07 },
  { asset: "FET", fee: 25 },
  { asset: "FIL", fee: 0.01 },
  { asset: "FLR", fee: 6 },
  { asset: "FLOW", fee: 0.03 },
  { asset: "FXS", fee: 0.65 },
  { asset: "GALA", fee: 140 },
  { asset: "GAL", fee: 2.9 },
  { asset: "GARI", fee: 5 },
  { asset: "GALA", fee: 140 },
  { asset: "GAL", fee: 2.9 },
  { asset: "GARI", fee: 5 },
  { asset: "GENS", fee: 30 },
  { asset: "MV", fee: 41 },
  { asset: "GTC", fee: 3.1 },
  { asset: "GMX", fee: 0.007 },
  { asset: "GNO", fee: 0.05 },
  { asset: "GST", fee: 10 },
  { asset: "FARM", fee: 0.16 },
  { asset: "HFT", fee: 9.3 },
  { asset: "HDX", fee: 3.5 },
  { asset: "IDEX", fee: 110 },
  { asset: "RLC", fee: 3.3 },
  { asset: "ICX", fee: 10 },
  { asset: "IMX", fee: 5.2 },
  { asset: "INJ", fee: 2 },
  { asset: "TEER", fee: 1 },
  { asset: "INTR", fee: 2 },
  { asset: "ICP", fee: 0.001 },
  { asset: "JASMY", fee: 920 },
  { asset: "JUNO", fee: 0.03 },
  { asset: "KAR", fee: 1 },
  { asset: "KAVA", fee: 0.15 },
  { asset: "KEEP", fee: 34 },
  { asset: "KP3R", fee: 0.071 },
  { asset: "ROOK", fee: 0.14 },
  { asset: "KILT", fee: 0.2 },
  { asset: "KIN", fee: 25000 },
  { asset: "KINT", fee: 0.1 },
  { asset: "KSM", fee: 0.01 },
  { asset: "KNC", fee: 7.5 },
  { asset: "LDO", fee: 2.5 },
  { asset: "LCX", fee: 81 },
  { asset: "LMWR", fee: 7 },
  { asset: "LSK", fee: 0.3 },
  { asset: "LTC", fee: 0.002 },
  { asset: "LPT", fee: 0.9 },
  { asset: "LRC", fee: 17 },
  { asset: "MKR", fee: 0.0078 },
  { asset: "MNGO", fee: 6 },
  { asset: "MSOL", fee: 0.005 },
  { asset: "POND", fee: 560 },
  { asset: "MASK", fee: 1.1 },
  { asset: "MC", fee: 18 },
  { asset: "MINA", fee: 0.05 },
  { asset: "MIR", fee: 62 },
  { asset: "XMR", fee: 0.0001 },
  { asset: "GLMR", fee: 0.15 },
  { asset: "MOVR", fee: 0.07 },
  { asset: "MOON", fee: 1 },
  { asset: "MULTI", fee: 0.54 },
  { asset: "EGLD", fee: 0.05 },
  { asset: "MXC", fee: 300 },
  { asset: "ALICE", fee: 3.4 },
  { asset: "NANO", fee: 0.05 },
  { asset: "NEAR", fee: 0.01 },
  { asset: "NODL", fee: 25 },
  { asset: "NMR", fee: 0.31 },
  { asset: "NYM", fee: 1 },
  { asset: "OCEAN", fee: 15 },
  { asset: "OMG", fee: 4.1 },
  { asset: "OP", fee: 0.25 },
  { asset: "ORCA", fee: 0.25 },
  { asset: "OXT", fee: 66 },
  { asset: "OGN", fee: 46 },
  { asset: "OTP", fee: 0.5 },
  { asset: "OXY", fee: 5 },
  { asset: "PARA", fee: 25 },
  { asset: "PAXG", fee: 0.0029 },
  { asset: "PYUSD", fee: 5 },
  { asset: "PEPE", fee: 1000000 },
  { asset: "PERP", fee: 6.9 },
  { asset: "PHA", fee: 0.07 },
  { asset: "PICA", fee: 20 },
  { asset: "PLA", fee: 26 },
  { asset: "DOT", fee: 0.05 },
  { asset: "POLS", fee: 13 },
  { asset: "MATIC", fee: 4 }, // For ERC-20
  { asset: "POWR", fee: 30 },
  { asset: "PSTAKE", fee: 67 },
  { asset: "QTUM", fee: 0.01 },
  { asset: "QNT", fee: 0.047 },
  { asset: "RAD", fee: 3.1 },
  { asset: "RAY", fee: 0.5 },
  { asset: "RARI", fee: 3.6 },
  { asset: "REN", fee: 57 },
  { asset: "RNDR", fee: 3.7 },
  { asset: "REQ", fee: 56 },
  { asset: "XRP", fee: 0.2 },
  { asset: "XRT", fee: 0.2 },
  { asset: "RPL", fee: 0.13 },
  { asset: "RBC", fee: 330 },
  { asset: "SBR", fee: 100 },
  { asset: "SAMO", fee: 30 },
  { asset: "SCRT", fee: 0.5 },
  { asset: "SEI", fee: 1 },
  { asset: "KEY", fee: 670 },
  { asset: "SRM", fee: 10 },
  { asset: "SHIB", fee: 400000 },
  { asset: "SDN", fee: 7 },
  { asset: "SC", fee: 5 },
  { asset: "SOL", fee: 0.01 },
  { asset: "SGB", fee: 0.01 },
  { asset: "SPELL", fee: 7500 },
  { asset: "STX", fee: 0.25 },
  { asset: "FIS", fee: 11 },
  { asset: "ATLAS", fee: 75 },
  { asset: "POLIS", fee: 1 },
  { asset: "STG", fee: 7 },
  { asset: "ALPHA", fee: 48 },
  { asset: "XLM", fee: 0.001 },
  { asset: "STEP", fee: 10 },
  { asset: "GMT", fee: 0.5 },
  { asset: "STORJ", fee: 15 },
  { asset: "SUI", fee: 0.25 },
  { asset: "SUPER", fee: 41 },
  { asset: "RARE", fee: 47 },
  { asset: "SUSHI", fee: 5.1 },
  { asset: "SXP", fee: 11 },
  { asset: "SYN", fee: 6.7 },
  { asset: "SNX", fee: 2.2 },
  { asset: "TBTC", fee: 0.0002 },
  { asset: "LUNA2", fee: 0.1 },
  { asset: "TVK", fee: 130 },
  { asset: "EURT", fee: 7 },
  { asset: "USDT", fee: 2 },
  { asset: "USDT-ERC20", fee: 8 },
  { asset: "USDT-Polygon", fee: 1 },
  { asset: "USDT-Solana", fee: 1 },
  { asset: "USDT-TRC20", fee: 3 },
  { asset: "XTZ", fee: 0.4 },
  { asset: "GRT", fee: 39 },
  { asset: "SAND", fee: 8.8 },
  { asset: "RUNE", fee: 0.5 },
  { asset: "T", fee: 160 },
  { asset: "TRU", fee: 81 },
  { asset: "TUSD", fee: 3 },
  { asset: "TOKE", fee: 5.8 },
  { asset: "TRX", fee: 15 },
  { asset: "UNI", fee: 0.94 },
  { asset: "UNFI", fee: 1.2 },
  { asset: "UMA", fee: 2.8 },
  { asset: "USDC", fee: 5 },
  { asset: "USDC-ERC20", fee: 8 },
  { asset: "USDC-Polygon", fee: 1 },
  { asset: "USDC-Solana", fee: 1 },
  { asset: "USDC-TRC20", fee: 3 },
  { asset: "WAVES", fee: 0.005 },
  { asset: "WOO", fee: 23 },
  { asset: "WBTC", fee: 0.0002 },
  { asset: "WETH", fee: 0.003 },
  { asset: "WAXL", fee: 11 },
  { asset: "YFI", fee: 0.00064 },
  { asset: "YGG", fee: 21 },
  { asset: "ZEC", fee: 0.001 },
];
const bitstampWidrawalFees = [
  { asset: "BCH", fee: 0.0001 },
  { asset: "BTC", fee: 0.0005 },
  { asset: "ETH", fee: 0.006 },
  { asset: "LTC", fee: 0.001 },
  { asset: "PAX", fee: 20 },
  { asset: "XLM", fee: 0.005 },
  { asset: "XRP", fee: 0.02 },
  { asset: "LINK", fee: 1.5 },
  { asset: "OMG", fee: 3 },
  { asset: "USDC", fee: 20 },
  { asset: "USDC_XLM", fee: 1 },
  { asset: "AAVE", fee: 0.2 },
  { asset: "BAT", fee: 25 },
  { asset: "UMA", fee: 2 },
  { asset: "DAI", fee: 15 },
  { asset: "KNC", fee: 15 },
  { asset: "MKR", fee: 0.005 },
  { asset: "ZRX", fee: 12 },
  { asset: "GUSD", fee: 1 },
  { asset: "ALGO", fee: 0.1 },
  { asset: "AUDIO", fee: 10 },
  { asset: "CRV", fee: 7 },
  { asset: "SNX", fee: 4 },
  { asset: "UNI", fee: 2 },
  { asset: "YFI", fee: 0.0007 },
  { asset: "COMP", fee: 0.1 },
  { asset: "GRT", fee: 22 },
  { asset: "LRC", fee: 15 },
  { asset: "USDT", fee: 20 },
  { asset: "EURT", fee: 2 },
  { asset: "FLR", fee: 2 },
  { asset: "MANA", fee: 6 },
  { asset: "MATIC", fee: 15 },
  { asset: "SUSHI", fee: 1.5 },
  { asset: "CHZ", fee: 75 },
  { asset: "ENJ", fee: 9 },
  { asset: "HBAR", fee: 1 },
  { asset: "ALPHA", fee: 30 },
  { asset: "AXS", fee: 0.15 },
  { asset: "FTT", fee: 0.6 },
  { asset: "SAND", fee: 6 },
  { asset: "STORJ", fee: 15 },
  { asset: "ADA", fee: 1 },
  { asset: "FET", fee: 20 },
  { asset: "RGT", fee: 1 },
  { asset: "SKL", fee: 98 },
  { asset: "CEL", fee: 7 },
  { asset: "SLP", fee: 1500 },
  { asset: "SXP", fee: 12 },
  { asset: "SGB", fee: 0.1 },
  { asset: "AVAX", fee: 0.01 },
  { asset: "DYDX", fee: 3 },
  { asset: "FTM", fee: 5 },
  { asset: "SHIB", fee: 400000 },
  { asset: "AMP", fee: 340 },
  { asset: "ENS", fee: 1 },
  { asset: "GALA", fee: 40 },
  { asset: "PERP", fee: 2.5 },
  { asset: "WBTC", fee: 0.000318 },
  { asset: "CTSI", fee: 35 },
  { asset: "CVX", fee: 0.6 },
  { asset: "IMX", fee: 5 },
  { asset: "NEXO", fee: 8 },
  { asset: "UST", fee: 15 },
  { asset: "ANT", fee: 3 },
  { asset: "GODS", fee: 15 },
  { asset: "RAD", fee: 3 },
  { asset: "BAND", fee: 4 },
  { asset: "INJ", fee: 3 },
  { asset: "RLY", fee: 80 },
  { asset: "RNDR", fee: 7 },
  { asset: "VEGA", fee: 5 },
  { asset: "1INCH", fee: 10 },
  { asset: "SOL", fee: 0.01 },
  { asset: "BOBA", fee: 10 },
  { asset: "APE", fee: 2 },
  { asset: "MPL", fee: 0.6 },
  { asset: "EUROC", fee: 5 },
  { asset: "DOT", fee: 2 },
  { asset: "NEAR", fee: 0.005 },
  { asset: "LDO", fee: 9 },
  { asset: "DGLD", fee: 0.005 },
  { asset: "DOGE", fee: 4 },
  { asset: "SUI", fee: 0.2 },
  { asset: "PYUSD", fee: 5 },
];
