---
version: "3"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
      - $PWD/rabbitmq/log/:/var/log/rabbitmq
    ports:
      - ${RABBITMQ_HOST}:${RABBITMQ_PORT}:5672
      - 127.0.0.1:15672:15672
    networks:
      - cryptoTracker

volumes:
  rabbitmq:
    external: false

networks:
  cryptoTracker:
    driver: bridge
